# Generated by Django 3.2.4 on 2023-05-16 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='artist',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('artistid', models.IntegerField(primary_key=True, serialize=False)),
                ('doj', models.DateTimeField()),
            ],
            options={
                'ordering': ('-doj',),
            },
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('passwd', models.CharField(max_length=25)),
                ('doj', models.DateTimeField()),
            ],
            options={
                'ordering': ('-doj',),
            },
        ),
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.customer')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='song',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('artists', models.CharField(max_length=100)),
                ('duration_s', models.IntegerField()),
                ('songid', models.IntegerField(primary_key=True, serialize=False)),
                ('doa', models.DateTimeField()),
                ('artistid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='player.artist')),
            ],
            options={
                'ordering': ('-doa',),
            },
        ),
        migrations.CreateModel(
            name='playlist_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.playlist')),
                ('playlist_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.song')),
            ],
        ),
    ]
